main: main.cpp
	g++ -std=c++11 main.cpp -o main -I ../../libigl/include -I ../../libigl/external/nanogui/ext/eigen -I ../../libigl/external/nanogui/ext/glew -I ../../libigl/external/nanogui/ext/glfw -L ../../libigl/external/nanogui/ext/glew -L ../../libigl/external/nanogui/ext/glfw  -lGL -lglfw -lGLEW

clean:
	rm -f main
